### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yaalsn**
add MacOS installation instructions in README

### CODE REVIEW

**Comment by DeanChan** [comment]
Hi there. Thank you for the instruction.

ossfs successfully compiled on my M1 Macbook Air, and the mount command (`sudo ossfs bucketname ~/Desktop/Sync -o url=http://oss-cn-hangzhou-zmf.aliyuncs.com/`) shows no warning and error.  `df -h` shows the bucket is successfully mounted. (`ossfs@macfuse0   64Gi    0Bi   64Gi     0%       0          0  100%   /Users/username/Desktop/Sync`)

However, when doing `ls ~/Desktop/Sync`, an error message shows like this: `ls: Desktop/Sync: No such file or directory`. Also, this path disappears completely in Finder.

Do you have any idea about this error?

Thanks.

**Comment by yaalsn** [comment]
> Hi there. Thank you for the instruction.
> 
> ossfs successfully compiled on my M1 Macbook Air, and the mount command (`sudo ossfs bucketname ~/Desktop/Sync -o url=http://oss-cn-hangzhou-zmf.aliyuncs.com/`) shows no warning and error. `df -h` shows the bucket is successfully mounted. (`ossfs@macfuse0 64Gi 0Bi 64Gi 0% 0 0 100% /Users/username/Desktop/Sync`)
> 
> However, when doing `ls ~/Desktop/Sync`, an error message shows like this: `ls: Desktop/Sync: No such file or directory`. Also, this path disappears completely in Finder.
> 
> Do you have any idea about this error?
> 
> Thanks.

Sorry, I have no idea about compiling `ossfs` on Apple M1 processor. Have you tried upgrading  `macFuse` to the latest version? If not works, just to try this: https://techstuffer.com/fuse-for-macos-apple-silicon-m1/

**Comment by DeanChan** [comment]
Hi @yaalsn. Many thanks for your quick reply.

I already installed macFUSE according to the given link. The problem still exists.

**Comment by DeanChan** [comment]
Hi @yaalsn. I managed to fix this issue by removing the `sudo` before the `ossfs`.
I was being silly (QAQ)...

**Comment by yaalsn** [comment]
> Hi @yaalsn. I managed to fix this issue by removing the `sudo` before the `ossfs`.
> I was being silly (QAQ)...

"If you encounter difficulties, don’t do it and get a good sleep."              
                                            —— BOSS

**Pull request closed without merging**
